language: c
sudo: required
install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
script:
  - bash -ex .travis-opam.sh
env:
  global:
    - OCAML_VERSION=4.04
    - TESTS=false
    - PACKAGE=sm-cli
    - PINS="xapi-idl:git://github.com/xapi-project/xcp-idl#feature/REQ477/master xcp:git://github.com/xapi-project/xcp-idl#feature/REQ477/master"
  matrix:
    - BASE_REMOTE=git://github.com/xapi-project/xs-opam
    - EXTRA_REMOTES=git://github.com/xapi-project/xs-opam
matrix:
  fast_finish: true
  allow_failures:
    - env: EXTRA_REMOTES=git://github.com/xapi-project/xs-opam

